### ISSUE TITLE
Build Issue for 3.16.1 - '_Insert_n': is not a member of ... on MSVS 17 CE

### ISSUE THREAD

**Issue by JLudwig2552** [OpenVSP/OpenVSP#100]
Building with MSVS 17 Community Edition.

Ran cmake on the super projects target. Works as expected, no errors.
Load the sln file into MSVS 17 CE. 
Build the "ALL_BUILD" project.
The "Libraries" and "ZERO_CHECK" projects build without errors but the "OpenVSP" project fails with the following:

![eigen_error](https://user-images.githubusercontent.com/12434443/38811639-0935bd94-4158-11e8-9a4a-b92bbc0878fd.png)

I've tried building on 2 separate PC's. One running win 10, one running win 7. Both have the same errors. 

The error occurs compiling src/util/VspSurf.cpp.

**Comment by ramcdona** [comment]
Please test with version 3.19.0 and re-open if the problem persists.
