### ISSUE TITLE
Problem: Mass Prop Calculation on Windows 10

### ISSUE THREAD

**Issue by ge98fiy** [OpenVSP/OpenVSP#103]
Hey all, 

when trying to run the mass prop calculation on my aircraft model, I get incorrect results. The first time I run it everything works fine, but then OpenVSP takes different parts of the aircraft (instead of the whole aircraft) - apparently randomly - and calculates the overall center of gravity only with these parts. Sometimes it works correctly including all parts, but then again it doesn't work. I took some screenshots, so you can see what happens. First, I load my model, the run the mass prop calculation by clicking on compute. The first and second time I click on compute it works fine, but the subsequent times I click on compute it crashes. Except for run 5, where it works fine again. However, afterwards it crashes again. I used version 3.8.1. 
I tracked it down to a Windows 10 vs Windows 7 problem - it didn't happen on my old PC (Win7). However, on my new one (Win 10) it does it all the time. I tried on a second Win 10 and get same problems. On three other Win 7 PC's it works just fine. 
I would appreciate your help, as I am using the mass prop calculation within an aircraft design process which I'd be happy to use on my new Win 10 PC. 
Kind regards,
Anna

First and second run:
![openvsp_massprops_run1_2](https://user-images.githubusercontent.com/39701710/40617269-28727c54-628e-11e8-8ec2-010f8fd9430d.JPG)
Third run:
![openvsp_massprops_run3](https://user-images.githubusercontent.com/39701710/40617271-28915124-628e-11e8-9a7c-4814028647e4.JPG)
Fourth run:
![openvsp_massprops_run4](https://user-images.githubusercontent.com/39701710/40617272-28ac16b2-628e-11e8-9a1c-f07635c04a1f.JPG)
Fifth run:
![openvsp_massprops_run5](https://user-images.githubusercontent.com/39701710/40617273-28ca049c-628e-11e8-99dd-eaf14ea3d77b.JPG)

**Comment by ramcdona** [comment]
Notice that a new MeshGeom is added to the Geom Browser each time you run Mass Properties.  These perfectly overlap and then cause problems with the slicing and intersection algorithm.  Delete each one before you re-run Mass Properties adn you should be fine.

**Comment by ge98fiy** [comment]
Okay, thank you. Is there a command to delete all previous meshes that I can use when using OpenVSP without GUI? Thanks in advance!

**Comment by ramcdona** [comment]
One of the results returned by the ResultsMgr is the GeomID of the new
MeshGeom that was created.  You should be able to DeleteGeom that ID.

Rob

**Comment by ge98fiy** [comment]
Hey Rob,
finally I found the time to continue working on this issue and I found that deleting the previous meshes does not help. The random part selection also happens when I load the complete aircraft and then do a mass prop calculation (without having computed the mass props before). Sometimes all parts are taken and sometimes not (see attached figures as examples - both are taken directly after the mass prop calculation of the newly loaded configuration). This time I used the newest release (3.16.2). Do you have an idea of why this is happening? Thanks for your help!
![openvsp_massprops_run1_1_feb19](https://user-images.githubusercontent.com/39701710/53492401-10eebf00-3a99-11e9-91e1-97df2961c9aa.JPG)
![openvsp_massprops_run1_3_feb19](https://user-images.githubusercontent.com/39701710/53492409-14824600-3a99-11e9-942b-09eb31e0a947.JPG)

**Comment by ramcdona** [comment]
Can you share the file that you're working with?

Thanks,

Rob

**Comment by ge98fiy** [comment]
Hey Rob,

please find the file attached. I’ve just tried it again and it worked the first 5 five times when loading it, but then it failed again…

Thank you very much for your help,
Anna

Von: Rob McDonald [mailto:notifications@github.com]
Gesendet: Donnerstag, 28. Februar 2019 17:32
An: OpenVSP/OpenVSP <OpenVSP@noreply.github.com>
Cc: Scholz, Anna <anna.scholz@tum.de>; Author <author@noreply.github.com>
Betreff: Re: [OpenVSP/OpenVSP] Problem: Mass Prop Calculation on Windows 10 (#103)

Can you share the file that you're working with?

Thanks,

Rob

**Comment by ge98fiy** [comment]
Hey Rob,
just want to make sure you received the file as I haven't heard back from you.
Thanks in advance,
Anna

**Comment by ramcdona** [comment]
Sorry Anna -- I saw the email you intended to attach the file to, but no
file was attached.

Rob

**Comment by ge98fiy** [comment]
Oh okay, sorry! Actually I am not quite sure how to send you a .vsp3 file, cause GIT tells me I can only attach jpegs or text files to my messages and I am not allowed to upload any files to the repository. So what I did is to rename the .vsp3 file to .txt and I hope you can still use it! Cheers, Anna
[A320.txt](https://github.com/OpenVSP/OpenVSP/files/2965586/A320.txt)

**Comment by ge98fiy** [comment]
Hey Rob, 
did you find the time to have a look at the problem? 
Thanks,
Anna
