### ISSUE TITLE
 error: ‘piecewise_binary_cubic_creator’ in namespace ‘eli::geom::curve’ does not name a template type

### ISSUE THREAD

**Issue by jiapei100** [OpenVSP/OpenVSP#110]
A but of such ERRORs... seems to have something to do with Code-Eli ???
Please refer to [https://github.com/ddmarshall/Code-Eli/issues/58](https://github.com/ddmarshall/Code-Eli/issues/58)

```
....../OpenVSP/src/util/Vsp1DCurve.cpp:29:27: error: ‘piecewise_binary_cubic_creator’ in namespace ‘eli::geom::curve’ does not name a template type
 typedef eli::geom::curve::piecewise_binary_cubic_creator<double, 1, oned_curve_tolerance_type> oned_piecewise_binary_cubic_creator;
```

Did anybody meet the same issue?

Cheers
Pei

**Comment by ramcdona** [comment]
Please test with version 3.19.0 and re-open if the problem persists.
