### ISSUE TITLE
Links don't save

### ISSUE THREAD

**Issue by N22YF** [OpenVSP/OpenVSP#114]
I've noticed, with some files, when I add links, if I save the file and reopen it, the links will be gone and I'll have to recreate them (although they'll be gone again when I save and reopen the file).

**Comment by ramcdona** [comment]
Anything special about the files or the Parms involved in the links?  Does a warning message about remapping ID's pop up for these files?  User defined Parms are somewhat unusual.  Files constructed by 'inserting' other files are also somewhat unusual.

Parm IDs are supposed to be unique and stable.  When a file loads and sets up links (or any time the model updates) the IDs are checked -- if a link involves invalid ID's, the link is destroyed.

So, this makes it sound like your ID's aren't as stable as they are supposed to be.  You might try opening the file, and then save-as a different name -- then run diff to compare the two files.  They should be identical -- if they aren't, that will provide clues.

This is a small consolation, but you can save the code from an advanced link off to make it easier to re-create if it gets destroyed.

**Comment by N22YF** [comment]
Thanks! Nothing special about the file or the Parms involved, as far as I know. No user-defined Parms, and I didn't insert any other files. But yes, when I open the file, I get the message in the console window
`. Error:  Unexpected intermediate ResetRemapID.`

When I save-as a different name, the new file is not identical to the original:
- The `Vehicle\ParmContainer\AdjustView` sub-element attributes differ
- A `Vehicle\ParmContainer\FitModel` element is missing in the newly-saved file
- The `Set_List` element in various places throughout the file has different attributes
- The contents of `LinkMgr\Link\ParmAID` and `LinkMgr\Link\ParmBID` differ
- The newly-saved file contains new `StructureMgr\FeaPropertyInfo\ParmContainer` elements

**Comment by ZachHazen** [comment]
Just getting started with openVSP today I received a similar message when opening the eCRM-001_v3.vsp3 "Unexpected intermediate ResetRemapID" - using openVSP 3.16.2

**Comment by ramcdona** [comment]
RIP my friend.  I believe this issue was resolved.
