### ISSUE TITLE
Mass Prop Calculation Issue Win10 - reopened

### ISSUE THREAD

**Issue by ge98fiy** [OpenVSP/OpenVSP#117]
Hey Rob,
finally I found the time to continue working on this issue and I found that deleting the previous meshes does not help. The random part selection also happens when I load the complete aircraft and then do a mass prop calculation (without having computed the mass props before). Sometimes all parts are taken and sometimes not (see attached figures as examples - both are taken directly after the mass prop calculation of the newly loaded configuration). This time I used the newest release (3.16.2). Do you have an idea of why this is happening? Thanks for your help!
![openvsp_massprops_run1_1_feb19](https://user-images.githubusercontent.com/39701710/53492401-10eebf00-3a99-11e9-91e1-97df2961c9aa.JPG)
![openvsp_massprops_run1_3_feb19](https://user-images.githubusercontent.com/39701710/53492409-14824600-3a99-11e9-942b-09eb31e0a947.JPG)

_Originally posted by @ge98fiy in https://github.com/OpenVSP/OpenVSP/issues/103#issuecomment-467855362_

**Comment by ge98fiy** [comment]
Hey Rob, 
did you find the time to have a look at the problem? 
Thanks,
Anna

**Comment by ramcdona** [comment]
If you are still having general problems, please post a question to the Google Group -- possibly including a test file.

If you have a specific bug with directions of how to exactly reproduce it, please open a new issue here.
