### ISSUE TITLE
Helicopter Analysis with VSP

### ISSUE THREAD

**Issue by tufan2005** [OpenVSP/OpenVSP#119]
Dear Friend

I want to do analysis VSTOL aircraft like helicopter. I can perform this type aircraft. Because helicopter have main rotor, air go through up to down, and has tail rotor air go through right to left.

I can simulate this situation or like that situation with VSPAERO? 

Could you help or inform me?

**Comment by ramcdona** [comment]
If you are satisfied with a rigid rotor analysis, this kind of analysis can be done with VSPAERO.

Questions like this are best asked on the OpenVSP Google Group.

If you have a specific bug to report -- with a reproducible test case, then please open an issue for that bug report.
