### ISSUE TITLE
Wrong path returne by PathToExe() in case of API calls

### ISSUE THREAD

**Issue by delonguevils** [OpenVSP/OpenVSP#120]
I think there is still an issue linked to the call of the `PathToExe()` function from the python API 

In issue #89, you wrote that:

> In the case of the Python API, it expects these to be in the same place as the _vsp.so binary file.

However, for the trials I made with the python API (OpenVSP_3.16.1 or OpenVSP_3.16.2, on windows and Linux computers), `PathToExe()` seems to return the **path to the python executable file**, instead of the path where _vsp.so is located. This means that, the python API searches (and try to run) vspaero, vspviewer, and vspslicer binaries in `C:\Anaconda2\` or `/usr/bin` (for example), instead of the location of the _vsp.so file, as you suggested.

This seems to be a bug specific to the python API, because running vspaero from the GUI of vsp leads to the expected behavior (m_ExePath  = ...`/OpenVSP/build/vsp`, which is the location of the vsp binary).

Would that not be preferable that, in case of use of the Python API, `PathToExe()` (or `m_ExePath`) would return/point to the location of _vsp.so or vsp.py ?

**Comment by ramcdona** [comment]
Please try this with a recent version of OpenVSP.  The current versions of the package should discover where they're installed and set the paths appropriately.  And, the most recent version should install the VSPAERO files to the right place.

If not, please ask a question on the Google Group or re-open a new issue.
