### ISSUE TITLE
cant add Disk use python？

### ISSUE THREAD

**Issue by WhaleHu** [OpenVSP/OpenVSP#122]
![24fb37a656c89d21e70bf26a791696e](https://user-images.githubusercontent.com/22174603/55461475-1bb3eb00-5627-11e9-8526-63b636ea5622.jpg)
return empty

**Comment by ramcdona** [comment]
This is most likely a problem with the Python API not being able to find the custom geometry.  Call 

gtypes = openvsp.GetGeomTypes(); 

and then print out everything in gtypes (a list of strings).  If Disk does not appear, then you can't add it and you need to resolve the paths issue.  Othewise, something else is wrong.

This kind of question is best asked on the Google Group.  If you're still having trouble, please ask there.

If you have a specific bug to report with a reproducible test case, please open a new issue for it.
