### ISSUE TITLE
Secondary y-axis obscures part of graph in VSPAERO results viewer

### ISSUE THREAD

**Issue by iforce2d** [OpenVSP/OpenVSP#128]
Example (axis titled "[Y]" on right hand side obscures some of the graph):
![Wrong](http://www.iforce2d.net/tmp/vspViewerWrong.png)

I believe this is the correct result:
![Correct](http://www.iforce2d.net/tmp/vspViewerCorrect.png)

I was able to prevent this by commenting out the section at the bottom of this function that creates 'y2axis':
Vsp_Canvas* GroupLayout::AddCanvas

**Comment by ramcdona** [comment]
Fixed by 4385534b0dfb6495fcdecb8fedc6644a2bf1e05a
