### ISSUE TITLE
NoShow bug?

### ISSUE THREAD

**Issue by maximumQ** [OpenVSP/OpenVSP#13]
When setting a component to "NoShow", it still is visible when any of the Glass materials are selected.  Selecting any other material makes it disappear.  
![Before-maximumq](https://f.cloud.github.com/assets/2745682/438913/7f747dd6-b0d7-11e2-890e-afa52f2656d2.png)
![After-maximumq](https://f.cloud.github.com/assets/2745682/438914/80d047c8-b0d7-11e2-9f74-1b8a718aef8a.png)

**Comment by ramcdona** [comment]
This bug is fixed in v3.
