### ISSUE TITLE
Second monitor flicker

### ISSUE THREAD

**Issue by maximumQ** [OpenVSP/OpenVSP#14]
When booting up openVSP with a PC two-monitor setup, all the top menus on every open instance of windows blink and change slightly.   Then all of the drop-down menus (in outlook, firefox, excel, etc) on the second monitor flicker on and off, making it pretty hard to select an item from that menu.   Moving the application to the primary monitor solves the blinking drop-down as does closing the instance of VSP. 

Thanks! 
Andy

**Comment by ramcdona** [comment]
Please test with a recent version (say 3.19.0) and re-open if the problem persists.
