### ISSUE TITLE
STL import failure: ASCII STL works, binary STL fails

### ISSUE THREAD

**Issue by TTN-** [OpenVSP/OpenVSP#145]
When trying to import a binary format STL file it will not open. 

However if I save my STL file as ASCII format when exporting from my CAD, OpenVSP can open it.

Hope that helps someone out there.

**Comment by ramcdona** [comment]
Can you provide a small example file that fails for you?

**Comment by ramcdona** [comment]
Closing this file as the developers can not reproduce the problem.  Please re-open if you can post a small file that demonstrates the issue.
