### ISSUE TITLE
VSP hangs while a web browser is launched from the "Link to FEA Mesh Wiki Documentation"

### ISSUE THREAD

**Issue by trelau** [OpenVSP/OpenVSP#147]
When I close the browser, VSP becomes responsive.

**Comment by justingravett** [comment]
Thank you for the bug report. I just tested from Win64 and it worked fine, but on my Linux VM the button does nothing. The behavior is the same for the Parasite Drag GUI Wiki link. What operating system are you running?

**Comment by trelau** [comment]
Windows 10 64-bit. But, my laptop at the time of this issue was plugged into a Dell dock connected to external monitors. I just tried again on my laptop monitor and not connected to the dock, and things seem to work ok. Strange.
