### ISSUE TITLE
Dihedral and foil rotation at root

### ISSUE THREAD

**Issue by maximumQ** [OpenVSP/OpenVSP#15]
Add a stock MS_Wing.  
Change the root dihedral to 6°.
Rotate foil to match dihedral on root section. 
Run CompGeom.  (it should work)
Increase tesselation to 101 (from 21). 
Run CompGeom.  (it hardcrashes on my version)

Windows7
VSP 2.2.4

**Comment by ramcdona** [comment]
Please test with a recent version (say 3.19.0) and re-open if the problem persists.
