### ISSUE TITLE
error in SuperEllips

### ISSUE THREAD

**Issue by marcovanderbijl** [OpenVSP/OpenVSP#157]
please see thread
[https://groups.google.com/forum/#!topic/openvsp/w2DIA6jRM04]
for the .vsp3 file with the example

Please view the attached .vsp file in Left view, with the Circle as wireframe and the supEllips as shaded in glasslight material (this makes the discrepancy easy to see).
With the SuperEllips MaxWLoc at zero and tick for T/B symmetry swiched on, the SuperEllips ought to be symmetric at topside vs bottom.
Assuming the Circle is a true Circle.
I eyeballed the front-top-side of the SuperEllips reasonably correct to the curvature of the Circle by changing the SuperEllips N value.
But the bottom of the SuperEllips now shows a larger curvature.

**Comment by ramcdona** [comment]
Closed by 20cc92172367
