### ISSUE TITLE
Povray export creates *.inc file with improper syntax (according to povray 3.7)

### ISSUE THREAD

**Issue by fishforbreakfast** [OpenVSP/OpenVSP#16]
After exporting from vsp in povray format and then trying to render using povray, povray exits with an error about "curly braces" in the wrong place.  When examining the *.inc file generated by vsp the following syntax is observed:

smooth_triangle { 
<  10.30067305,    0.94447948,    0.27368970 >, <  -0.09548104,   -0.08715583,   -0.99160841 >,  
<   9.20500360,    0.99899050,    0.37439952 >, <  -0.09548104,   -0.08715583,   -0.99160841 >,  
<   9.20291231,    1.44043215,    0.33580108 >, <   0.17061100,    0.98476138,   -0.03371825 >  }
smooth_triangle { 
<   9.20500360,    0.99899050,    0.37439952 >, <  -0.09548104,   -0.08715583,   -0.99160841 >,  
<   8.17819106,    1.60517618,    0.41999061 >, <   0.13765366,    0.99031990,   -0.01783180 >  }
<   9.20291231,    1.44043215,    0.33580108 >, <   0.17061100,    0.98476138,   -0.03371825 >,  

The first entry has the curly brace at the end of the data.  The second entry has it before the data is finished.  Povray produces the following output (from xpe front end to povray):

==== [Parsing...] ==========================================================
File '/home/fred/Documents/Aircraft/TandemWing-3-3.inc' line 3: Parse Warning:
 Normal vector in mesh cannot be zero - changing it to <1,0,0>.
File '/home/fred/Documents/Aircraft/TandemWing-3-3.inc' line 20: Parse Error:
 Expected 'numeric expression', } found instead
Fatal error in parser: Cannot parse input.
Render failed

I can correct the issue by changing the generated *.inc file but not being well versed at either perl, sed or other shell scripting, it's very difficult to change a file with hundreds or thousands of entries by hand.  Even with emacs.

Cheers,

Fred

**Comment by ramcdona** [comment]
Do you still have this problem with OpenVSP 3.2.2?
It looks like our default scene file is quite a bit out of date, but the geometry data looks OK to me.  If you're a PovRay user, I would be happy to update our scene file to something more appropriate if directed.

**Comment by fishforbreakfast** [comment]
Hi,

Sorry it took so long to get back to you on this.  Just lost my sister last Friday so it's been a frazzled week.
![top](https://cloud.githubusercontent.com/assets/5172854/9705351/7258e3b6-5487-11e5-9978-ef2b8e2949c4.png)




Anyway, I did an export of the top and transport examples
![transport](https://cloud.githubusercontent.com/assets/5172854/9705358/923fcdde-5487-11e5-9670-6db8066ce2bd.png)
 from 3.2.2.  When rendered from povray, the shapes seem to be good.  The lighting needs adjustment though.  Somewhat expected, I would guess.  Thank you for all of your work on this, by the way.

Take Care,

Fred

**Comment by ramcdona** [comment]
So sorry to hear of your loss.  No problem in the delay -- it took me far longer to note this issue.

If you have suggestions for the default lighting, I can easily incorporate them.  However, the whole point of PovRay is for the end user to care quite a lot about their lighting and materials, so I don't see the defaults as being all that important.
