### ISSUE TITLE
OPEN VSP

### ISSUE THREAD

**Issue by akshay16506** [OpenVSP/OpenVSP#169]
Hello,
I am trying to write a matlab code which would automatically calculate parasitic drag once given a vsp3 model, Air speed and altitude. 
Please help me in this.

**Comment by cibinjoseph** [comment]
You'll have better luck finding help posting on the Google groups [forum](https://groups.google.com/g/openvsp) for OpenVSP.
As for Matlab scripts, there are a few examples that might be of help in [examples/matlab](https://github.com/OpenVSP/OpenVSP/tree/main/examples/matlab)

**Comment by ramcdona** [comment]
As Cibin mentioned, please ask questions like this to the Google Group.

Closed as it is not an issue.
