### ISSUE TITLE
Cant run VSP after installing on a Mac

### ISSUE THREAD

**Issue by smckamey** [OpenVSP/OpenVSP#17]
Mac OS 10.7
Installed VSP and libjpeg and I get the following error when I try to run VSP:

Last login: Thu Aug 15 11:02:23 on ttys002
Steves-MacBook-Pro:~ smckamey$ /Users/smckamey/Software/OpenVSP-2.2.4-MacOS/vsp ; exit;
Illegal instruction: 4
logout

[Process completed]

**Comment by ramcdona** [comment]
I believe 2.2.4 was accidentally built on 10.8.5.  I keep an old 10.7 machine around and try to build on it to prevent this from happening.  Update to 2.3.0 or even better 3.X.
