### ISSUE TITLE
Add capability to get Mesh_GeomID from ExportFile() in API

### ISSUE THREAD

**Issue by ajfield10** [OpenVSP/OpenVSP#183]
I'm using the API to export a set to STL, which works great. But it generates a mesh in the model I would like to delete, and I can't find a good way to grab the mesh ID.

One way to do this would be to have ExportFile return a results ID. The results from ExportFile could contain a result_name called Mesh_GeomID just like CompGeom. Potentially this requires allowing calls to ExportFile through the Analysis Manager?

The end result could look something like:
result_id = vsp.ExportFile(stlFullPath, set_id, vsp.EXPORT_STL)
mesh_id = vsp.GetStringResults( result_id, "Mesh_GeomID" ) 
vsp.DeleteGeomVec(mesh_id )

**Comment by justingravett** [comment]
This will be improved in the next release. ExportFile will return the ID of the MeshGeom generated in the export. If a particular export does not generate a mesh an empty string will be returned. The Mesh can then be deleted by calling "DeleteGeom" with the MeshGeom ID.
