### ISSUE TITLE
A value of -0.05 or more negative for a PropGeom blade crd_0 will crash OpenVSP

### ISSUE THREAD

**Issue by lsearl-thumpdataworks** [OpenVSP/OpenVSP#192]
OS: Unbutu 20.04.02 LTS
OpenVSP: 3.24.0

To reproduce:
1) In a new project, add a new prop geometry
2a) In the Blade tab, for the crd_0 value, move the slider to the left (smaller numbers), OpenVSP will crash.
Or
2b) Using the text box to enter a -0.05 or more negative number for crd_0 will also crash OpenVSP.

**Comment by justingravett** [comment]
Thanks for the bug report. This will be fixed in the next release.
