### ISSUE TITLE
Feature Request: mannequins

### ISSUE THREAD

**Issue by John-Bucknell** [OpenVSP/OpenVSP#20]
The VSP is a great tool for vehicle layout.  Having said that, I work on small vehicles and determining what the smallest acceptable size is requires a good estimate of human shapes.  I think it wouldn't be hard to code up a human shape with somewhat posable features, at least the major joints in side view - with scalable length and girth to represent the range of anatomies.

Thanks,

John

**Comment by ramcdona** [comment]
Version 3 includes user-defined components that can be shared via the Hangar.  Check out http://hangar.openvsp.org/vspfiles/280 to see if it meets your needs.
