### ISSUE TITLE
Building on Fedora linux

### ISSUE THREAD

**Issue by iforce2d** [OpenVSP/OpenVSP#206]
Not really an issue, just something that could be added to the documentation somewhere. I tested this on Fedora 33 and 34.

Follow the instructions as outlined here, with a few small changes: http://openvsp.org/wiki/doku.php?id=ubuntu_instructions

Install all required packages:

	dnf install gcc-c++ mesa-libGL-devel python3-devel git-gui cmake libxml2-devel fltk-devel cpptest-devel openjpeg-devel glm-devel eigen3-devel cminpack-devel glew-devel swig doxygen graphviz

When preparing build files for the libraries, use the FLTK included with OpenVSP source instead of the system FLTK, ie. change this cmake parameter to false:

	-DVSP_USE_SYSTEM_FLTK=false

For Fedora 34 that should be sufficient. For Fedora 33 and older, these changes are also necessary:

In these two files:

	repo/src/vsp/CMakeLists.txt
	repo/src/vsp_aero/viewer/CMakeLists.txt
        
... add the following extra system libraries to TARGET_LINK_LIBRARIES (for repo/src/vsp/CMakeLists.txt, add these for the 'vsp' and 'apitest_g' targets).

	dl
	Xft
	fontconfig
	Xrender
	Xinerama
	Xfixes
	Xcursor

**Comment by jeffallen** [comment]
You might be interested to see this new web page I wrote: https://openvsp.org/wiki/doku.php?id=rpm_instructions

**Comment by iforce2d** [comment]
Thanks Jeff, that sequence works for me (also F36)
