### ISSUE TITLE
How to set the deflection angle in the VPSAERO with an API?

### ISSUE THREAD

**Issue by TherebeForce** [OpenVSP/OpenVSP#209]
Does OpenVSP 3.25.0 have the function to set Control Group Angles with an API? It can create the control surface group by vspscript, but I can't figure out how to set control surface deflection angles with vspscript.

**Comment by justingravett** [comment]
Take a look at "VSPAERO_ActuatorDisk_CSGroup.vspscript" in the examples directory. There is also documentation for the API functions [here](http://openvsp.org/api_docs/latest/group___c_s_group.html)
