### ISSUE TITLE
vspaero "Carlson Pressure Correction" stall prediction not working

### ISSUE THREAD

**Issue by mah92** [OpenVSP/OpenVSP#213]
Hi
In WS 2021 video "VSPAERO - What's Next" a stall prediction algorithm was mentioned.
This feature seams to be added in vspaero, included in openvsp 3.26.0.
I added a default wing and fuselage to test this feature.
When setting the stall model to "Carlson Pressure Correction" nothing changes in Cl or Cd vs angles (I used 0 to 90 degrees) as if we have set the stall model to "none". Nothing changes in the viewer pressures visualization neither.
There seems to be no settings available for the "Carlson Pressure Correction" stall model.

**Comment by ramcdona** [comment]
The Google Group is a great place to ask questions like these.  That way, other users will be able to see the answers.

This CLmax method does not work for Mach=0.  You'll want to make sure your Mach value is reasonable for your velocity.  Even 0.1 will make a big difference.

Also, this method is sensitive to Reynolds number, so be sure to set Re to something appropriate, you will get very different stall behavior depending on Re.
