### ISSUE TITLE
Bug: wrong wetted volume/area calculation

### ISSUE THREAD

**Issue by 4random** [OpenVSP/OpenVSP#22]
1. Add Fuse
2. Change X Loc to 3
3. Select YZ symmetry
4. Execute comgeom
   -> for mirrored fuse wetted volume/area does not match the theoretical areas/volumes
   -> looking at the mesh (chose hidden instead of the default wire) one can see holes in the mesh

Same happens for
1. Add 2 Fuse on the same level
2. Change X Loc to 2 and -32
3. Execute compgeom

Chosing 3 and -33 as X Loc works fine (wetted = theoretical volume/area)

OpenVSP v2.3.0
Operating System: Windows 8

**Comment by ramcdona** [comment]
Please test with a recent version (say 3.19.0) and re-open if the problem persists.
