### ISSUE TITLE
Extraction error on vsp.exe from download OpenVSP 3.27.1 64-bit Python 3.6

### ISSUE THREAD

**Issue by BBFlyer1** [OpenVSP/OpenVSP#224]
From Download OpenVSP http://openvsp.org/download.php?msclkid=6dc0e68da89e11ec8444e8c895ac149f 
I downloaded OpenVSP 3.27.1 64-bit Python 3.6 today, 3-20-2022.  When I tried to extract it, as I have in the past, I got the following error:

“An unexpected error is keeping you from copying the file.  If you continue to receive this error, you can use the error code to search for help with this problem.
Error 0x800004005: Unspecified error

vsp
Type: Application
Date Modified 3/19/2022 6:05 AM
Size: 20.9 MB”

When I look at the vsp.exe properties using windows explorer, it says
 
File of Type: 	Application
Modified:	3/19/22 6:05 AM
Location:	OpenVSP-3.27.1-win64/
Size:		21,413 KB
Compressed:	11,164 KB
Method:	Deflated
CRC-32:	BE9DCC50
index:		161

Attributes:	[ ] read only	[ ] hidden	[ ] system

Everything else in the download seems to extract as expected.

I thought it might be an issue with just this version of OpenVSP, so I downloaded 
OpenVSP 3.27.1 64-bit Python 3.9.  When I extract vsp.exe from this version into a temporary folder, I get the extracted version of this program, 21 MB.  However, when I do the same with the  OpenVSP 3.27.1 64-bit Python 3.6 version, I get the above error message.

Please take a look.  Thanks

![Error Message](https://user-images.githubusercontent.com/35981529/159189597-44ccb939-4280-4981-b51b-2b1053f2293a.JPG)
![Extracting OpenVSP](https://user-images.githubusercontent.com/35981529/159189598-b972fca8-00ee-4ee4-9b30-554ba8554690.JPG)

**Comment by ramcdona** [comment]
This seems to be a problem with your computer decompressing files.  Other users have not had the same problem.

Are you still having the same trouble?  Can you reproduce the problem on another computer?

General questions like this are best directed to the OpenVSP Google Group.
