### ISSUE TITLE
Movie/Png still wonky

### ISSUE THREAD

**Issue by RichardPOuellette** [OpenVSP/OpenVSP#226]
version 3.27.1 option to save rotating prop movie or image fails. VSP runs through the 60 iterations, but does not save a file, either png or movie. ffmpeg is in path. Thoughts?
![image](https://user-images.githubusercontent.com/73549935/161123162-6e2d3725-6aca-466d-ae7c-5ced1a99b6bd.png)
![image](https://user-images.githubusercontent.com/73549935/161123281-81d28912-38a5-4a11-adce-4f5210acccc5.png)
![image](https://user-images.githubusercontent.com/73549935/161123478-f36b4833-2b53-4a88-a081-3a5830659a10.png)
[Rim-Fan(3.5inprop) - Copy.txt](https://github.com/OpenVSP/OpenVSP/files/8392125/Rim-Fan.3.5inprop.-.Copy.txt)

I included .vsp3 file by renaming it .txt to enable upload.

**Comment by ramcdona** [comment]
Rich - I worked on the movie export for 3.29.0 and fixed the problems I knew about.  Let me know if you still have trouble.
