### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Arthur19950212** [OpenVSP/OpenVSP#229]
Hello,I want to know whether openvsp use some transition function to judge flow transition.

besides, I want to know how could i import outside geometry in iges or stp format. It matters a lot to me. Thanks.

**Comment by ramcdona** [comment]
OpenVSP does not have a transition model.

There is a skin friction buildup tool where you can specify the transition Re.

OpenVSP is a geometry tool.  VSPAERO is a potential flow solver that has a very simple drag model in it.  That does not have a transition model.

OpenVSP can not import IGES or STEP files (it can export them).

Questions like this are best asked in the Google Group -- we try to use issues to track bugs.
