### ISSUE TITLE
VSP linker error - need FIND_PACKAGE(Threads)

### ISSUE THREAD

**Issue by mthiffau** [OpenVSP/OpenVSP#23]
Was trying to build OpenVSP for Arch Linux, the build got all the way to linking the VSP executable. I'm not sure why I didn't have this issue on Ubuntu, but on Arch, the VSP executable linking failed due to an undefined reference to pthread_create@GLIBC_X.X.X.... I checked the generated make files and found no -pthread in the linker line. I took a minute to learn how to fix this in CMake, the portable way is to use find_package and put the variable it creates into the link target list. I did this and it worked. I can provide the modified file if you like, but I'll assume you guys know more about it than I.

**Comment by acxz** [comment]
Hey @mthiffau I have fixed up the package for [openvsp](https://aur.archlinux.org/packages/openvsp/) on the AUR, if you would like to use it. I ended up compiling the SuperProject and did not run into the error you are facing.

**Comment by ramcdona** [comment]
Please follow the advice of the reply and/or test with a recent version (say 3.19.0) and re-open if the problem persists.
