### ISSUE TITLE
Could vspaero calculate the aerodynamics of aircrafts with slotted flap?

### ISSUE THREAD

**Issue by Arthur19950212** [OpenVSP/OpenVSP#231]
Could vspaero calculate the aerodynamics of aircrafts with slotted flap accurately. I find one case in workshop but find it may calculate wrong when i try a case.

**Comment by ramcdona** [comment]
This kind of question is best asked on the Google Group.

Erik Olsen has published a paper about modeling high lift systems in OpenVSP -- I am not sure if he went as far as VSPAERO.

VSPAERO is an inviscid, incompressible solver.  High lift flows are dominated by boundary layer behavior - and often have local supervelocities that are _much_ faster than the freestream.  They will always be a great challenge for a tool like VSPAERO.

At most VSPAERO may capture a shift in the lift curve -- the most advanced stall model might also have interesting results.  You will need to perform tests and compare with reference data to figure out where and how to best use the tool.
