### ISSUE TITLE
Trimmed surface coordinates

### ISSUE THREAD

**Issue by mjcarley** [OpenVSP/OpenVSP#233]
Using the trimmed surface analysis on simple geometries, the intersection curves for intersecting surfaces contain coordinates which lie outside the range (0,1) which seems incorrect for the Bezier surfaces. Is there a definition of the file format which states how these coordinates are to be interpreted?

**Comment by ramcdona** [comment]
Questions like this are probably best asked to the Google Group.

We mostly use the issue tracker to make sure bugs don't get lost over a longer time scale (so they don't get checked frequently).

OpenVSP uses piecewise Bezier surfaces - each quilt is made up of a bunch of patches.  Each patch has a parameter span that runs [0,1], these are scaled and combined to make the parameter space of a quilt.

Our parameters typically run [0,N] in the U direction (length of a fuselage, or out the span of a wing).  Where N is the number of segments.  Note that a common single segment wing actually has three segments -- the root cap, the main wing, and the tip cap - so the parameter will run [0,3].

Around the airfoil direction (or around the circumference of a fuselage), we run [0,4], with 2.0 representing the leading edge of an airfoil.

Our piecewise quilts get written as NURBS for STEP and IGES files by appropriately specifying the knots and the parameter values at the knots.  Any program that reads in a NURBS or STEP file should simultaneously read in the parameter limits for each surface.

When we show a U,V parameter to an OpenVSP user, we always scale them to [0,1].  We often have dual sets of API calls -- CompPnt(u,v) vs. CompPnt01(u,v) to make clear when the parameter space has been scaled to a [0,1] basis.

I recently had a user who had trouble with our exports on a [0,N] basis.  It looks like a bug in the receiving application, so I do not think we will make a change to [0,1] permanently, but there have been some other conversations in this area lately.
