### ISSUE TITLE
Planar Slice Ignoring Selected Set (3.30.0)

### ISSUE THREAD

**Issue by brandon-litherland** [OpenVSP/OpenVSP#237]
I found that Planar Slice (and Mass Prop) ignore the selected set and run the analysis on All or Shown only.  If any set other than All or Shown is selected, the All set is analyzed.  Shown set currently used as work-around in the GUI.  Uncertain if similar issue exists for the API.

**Comment by ramcdona** [comment]
I tried to duplicate this problem today and I can't get it to misbehave.  Perhaps you can email me the exact file that is failing.

Are you sure the components and Sets are set up the way you want?

I'm going to close for now.  Please re-open if you can replicate the problem.
