### ISSUE TITLE
OpenVSP2.3.0 fuselage and Ms wing cross section file problem! 

### ISSUE THREAD

**Issue by PanielNuaa** [OpenVSP/OpenVSP#24]
First, I want to build up a LD-6 container,see fig. below.
![ld6 container](https://cloud.githubusercontent.com/assets/7310626/2716437/70d62686-c52a-11e3-9b38-545bb876738c.jpg)
Then, I attend to use the 'FUSE' and the 'MS WING' to build it. As you know, we can choose the shape of the cross section( or an airfoil) from a flie. The files I choose are as follows, (upper for fuselage,lower for MS WiNG)
![fxs](https://cloud.githubusercontent.com/assets/7310626/2716471/34ab0c70-c52b-11e3-8525-8d39ecb6dd87.jpg)
![af](https://cloud.githubusercontent.com/assets/7310626/2716477/5b8f076a-c52b-11e3-861a-7d3d76099e77.jpg)
And the section plots in excel are as follows:
![excel cross section fxs](https://cloud.githubusercontent.com/assets/7310626/2716483/83019a88-c52b-11e3-85c2-534516ef019d.jpg)
![excel airfoil cross section af](https://cloud.githubusercontent.com/assets/7310626/2716492/a0de62fc-c52b-11e3-8dd6-b4c207f6c67e.jpg)
But when I did this in OpenVSP2.3.0, the cross section shapes are changed, the corners are 'cut off' or have more corners than I want, see the figs below:
![fuselage vsp](https://cloud.githubusercontent.com/assets/7310626/2716538/ce6621d2-c52c-11e3-982b-56ebbae38537.jpg)

![airfoil section vsp](https://cloud.githubusercontent.com/assets/7310626/2716508/16bc5e5c-c52c-11e3-9534-0bc2302ba89a.jpg)
I really don't how to deal with it! Is there some codes to round the corners in the VSP? What should I do to solve the problems? Or how to build a container in other ways?
Thank you ~~

**Comment by ramcdona** [comment]
Please test with a recent version (say 3.19.0) and re-open if the problem persists.  In particular, you may be interested in the Edit XSec type.
