### ISSUE TITLE
Using Openvsp API Script to show some geometry and not show others

### ISSUE THREAD

**Issue by YANG-DEMIN** [OpenVSP/OpenVSP#241]
Hi,
     I am using openvsp script to optimization my airplane. But when i try to make some geom shown and some not shown, i can not find the property function.
    The most similar function I found is "SetsetFlag" and visualization function. It work useless.

    Thank you very much!
     Good luck.
     YANG

**Comment by ramcdona** [comment]
You're on the right track with SetSetFlag.  There are two related sets -- we should generally keep them in a compatible state, but you can set them both to be safe.

// Hide geomid
SetSetFlag( geomid, SET_SHOWN, false );
SetSetFlag( geomid, SET_NOT_SHOWN, true );

You will likely need to call Update() after changing these values.

This kind of question is generally better asked on the Google Group.  Please follow up there if this doesn't work for you.

The issues are great for making sure something doesn't get lost or forgotten -- but they don't get checked very often, so it isn't great for quick answers.
