### ISSUE TITLE
ScreenGrab Failed: Not sure about the "VSP_USE_FLTK" Usage

### ISSUE THREAD

**Issue by YANG-DEMIN** [OpenVSP/OpenVSP#242]
Hi ,
I want to know how to define the VSP_USE_FLTK.
Thanks,
YANG
![image](https://user-images.githubusercontent.com/53554275/202881487-cabcb43d-34b6-43ac-afc0-7af6f59e0e18.png)

**Comment by ramcdona** [comment]
VSP_USE_FLTK is a compile-time option that is set by CMake when VSP_NO_GRAPHICS (another compile time option) is set.

These are true 99% of the time.

It is possible to compile OpenVSP without a GUI and without graphics support -- these options support that possibility.

Of course, without graphics, a screen grab is impossible.

What are you trying to accomplish?  Right now, to take a screen shot from a script environment, the OpenVSP GUI must be open -- which means screen captures are only available from the AngelScript scripting environment with OpenVSP running.

This kind of question is probably best asked on the Google Group.
