### ISSUE TITLE
ccx and cgx bit found

### ISSUE THREAD

**Issue by zufus** [OpenVSP/OpenVSP#245]
Hi,

when I launch vsp, a terminal window appears, and gives the following messages (I am translating them from Italian):

"ccx" not recognized as command, neither internal or external, and executable program or batch file
"cgx" not recognized as command, neither internal or external, and executable program or batch file"

This happens on openVSP version 3.31.1, Windows 10 64 bit.

**Comment by jeffallen** [comment]
This is a normal message, and nothing to worry about.

But maybe it would be better to remove these messages on startup and only show them later when the FEM analysis code actually tries to use the programs?

**Comment by ramcdona** [comment]
3.33.0 includes a fix that should silence this message.
