### ISSUE TITLE
Fuselage Conformal does not match parent shape in GENERAL_FUSELAGE Area or Height/Width mode

### ISSUE THREAD

**Issue by mumbricht** [OpenVSP/OpenVSP#246]
https://groups.google.com/g/openvsp/c/ykea4alzWzI

When making a general Fuselage XSec in area or height/width mode, the conformal does not offset correctly, and inverts with the parent surface.

**Comment by ramcdona** [comment]
I have this fixed locally, it will go into the next release.  If you need the fix sooner,[ this commit](https://github.com/OpenVSP/OpenVSP/commit/b9c425fa5a8c8aff8d5830bad9ea9f171d56fdc5) should do.
