### ISSUE TITLE
Build fails for 2.9.1

### ISSUE THREAD

**Issue by fishforbreakfast** [OpenVSP/OpenVSP#25]
Hi,

Just tried to build 2.9.1  The build fails at this point:

---

[ 14%] Building CXX object src/vsp_graphic/CMakeFiles/vsp_graphic.dir/src/ArcballCam.cpp.o
In file included from /usr/include/glm/gtc/quaternion.hpp:401:0,
                 from /usr/include/glm/gtc/epsilon.inl:30,
                 from /usr/include/glm/gtc/epsilon.hpp:99,
                 from /usr/include/glm/ext.hpp:67,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtc/quaternion.inl: In function 'glm::detail::tquat<T, P> glm::rotate(const glm::detail::tquat<T, P>&, const T&, const glm::detail::tvec3<T, P>&)':
/usr/include/glm/gtc/quaternion.inl:626:165: note: #pragma message: GLM: rotate function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: rotate function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                     ^
/usr/include/glm/gtc/quaternion.inl: In function 'T glm::roll(const glm::detail::tquat<T, P>&)':
/usr/include/glm/gtc/quaternion.inl:653:151: note: #pragma message: GLM: roll function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: roll function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                       ^
/usr/include/glm/gtc/quaternion.inl: In function 'T glm::pitch(const glm::detail::tquat<T, P>&)':
/usr/include/glm/gtc/quaternion.inl:667:152: note: #pragma message: GLM: pitch function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: pitch function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                        ^  
/usr/include/glm/gtc/quaternion.inl: In function 'T glm::yaw(const glm::detail::tquat<T, P>&)':  
/usr/include/glm/gtc/quaternion.inl:681:150: note: #pragma message: GLM: yaw function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.  
 #  pragma message("GLM: yaw function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")  
                                                                                                                                                      ^  
/usr/include/glm/gtc/quaternion.inl: In function 'T glm::angle(const glm::detail::tquat<T, P>&)':  
/usr/include/glm/gtc/quaternion.inl:811:152: note: #pragma message: GLM: angle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.  
 #  pragma message("GLM: angle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")  
                                                                                                                                                        ^  
/usr/include/glm/gtc/quaternion.inl: In function 'glm::detail::tquat<T, P> glm::angleAxis(const T&, const glm::detail::tvec3<T, P>&)':
/usr/include/glm/gtc/quaternion.inl:841:168: note: #pragma message: GLM: angleAxis function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: angleAxis function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                        ^
In file included from /usr/include/glm/gtc/matrix_transform.hpp:292:0,
                 from /usr/include/glm/ext.hpp:71,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtc/matrix_transform.inl: In function 'glm::detail::tmat4x4<T, P> glm::rotate(const glm::detail::tmat4x4<T, P>&, const T&, const glm::detail::tvec3<T, P>&)':
/usr/include/glm/gtc/matrix_transform.inl:58:165: note: #pragma message: GLM: rotate function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: rotate function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                     ^
/usr/include/glm/gtc/matrix_transform.inl: In function 'glm::detail::tmat4x4<T, P> glm::rotate_slow(const glm::detail::tmat4x4<T, P>&, const T&, const glm::detail::tvec3<T, P>&)':
/usr/include/glm/gtc/matrix_transform.inl:99:170: note: #pragma message: GLM: rotate_slow function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: rotate_slow function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                          ^
/usr/include/glm/gtc/matrix_transform.inl: In function 'glm::detail::tmat4x4<U, (glm::precision)0u> glm::perspective(const valType&, const valType&, const valType&, const valType&)':
/usr/include/glm/gtc/matrix_transform.inl:232:170: note: #pragma message: GLM: perspective function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: perspective function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                          ^
/usr/include/glm/gtc/matrix_transform.inl: In function 'glm::detail::tmat4x4<U, (glm::precision)0u> glm::perspectiveFov(const valType&, const valType&, const valType&, const valType&, const valType&)':
/usr/include/glm/gtc/matrix_transform.inl:264:173: note: #pragma message: GLM: perspectiveFov function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: perspectiveFov function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                             ^
/usr/include/glm/gtc/matrix_transform.inl: In function 'glm::detail::tmat4x4<U, (glm::precision)0u> glm::infinitePerspective(T, T, T)':
/usr/include/glm/gtc/matrix_transform.inl:290:178: note: #pragma message: GLM: infinitePerspective function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: infinitePerspective function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                                  ^
/usr/include/glm/gtc/matrix_transform.inl: In function 'glm::detail::tmat4x4<U, (glm::precision)0u> glm::tweakedInfinitePerspective(T, T, T)':
/usr/include/glm/gtc/matrix_transform.inl:318:185: note: #pragma message: GLM: tweakedInfinitePerspective function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: tweakedInfinitePerspective function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                                         ^
In file included from /usr/include/glm/gtx/polar_coordinates.hpp:70:0,
                 from /usr/include/glm/ext.hpp:116,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtx/polar_coordinates.inl: In function 'glm::detail::tvec3<T, P> glm::polar(const glm::detail::tvec3<T, P>&)':
/usr/include/glm/gtx/polar_coordinates.inl:28:152: note: #pragma message: GLM: polar function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: polar function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                        ^
/usr/include/glm/gtx/polar_coordinates.inl: In function 'glm::detail::tvec3<T, P> glm::euclidean(const glm::detail::tvec2<T, P>&)':
/usr/include/glm/gtx/polar_coordinates.inl:46:167: note: #pragma message: GLM: euclidean function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: euclidean function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                       ^
In file included from /usr/include/glm/gtx/rotate_vector.hpp:130:0,
                 from /usr/include/glm/ext.hpp:120,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtx/rotate_vector.inl: In function 'glm::detail::tvec2<T, P> glm::rotate(const glm::detail::tvec2<T, P>&, const T&)':
/usr/include/glm/gtx/rotate_vector.inl:24:164: note: #pragma message: GLM: rotate function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: rotate function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                    ^
/usr/include/glm/gtx/rotate_vector.inl: In function 'glm::detail::tvec3<T, P> glm::rotateX(const glm::detail::tvec3<T, P>&, const T&)':
/usr/include/glm/gtx/rotate_vector.inl:79:165: note: #pragma message: GLM: rotateX function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: rotateX function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                     ^
/usr/include/glm/gtx/rotate_vector.inl: In function 'glm::detail::tvec3<T, P> glm::rotateY(const glm::detail::tvec3<T, P>&, const T&)':
/usr/include/glm/gtx/rotate_vector.inl:102:165: note: #pragma message: GLM: rotateY function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: rotateY function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                     ^
/usr/include/glm/gtx/rotate_vector.inl: In function 'glm::detail::tvec3<T, P> glm::rotateZ(const glm::detail::tvec3<T, P>&, const T&)':
/usr/include/glm/gtx/rotate_vector.inl:125:165: note: #pragma message: GLM: rotateZ function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: rotateZ function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                     ^
/usr/include/glm/gtx/rotate_vector.inl: In function 'glm::detail::tvec4<T, P> glm::rotateX(const glm::detail::tvec4<T, P>&, const T&)':
/usr/include/glm/gtx/rotate_vector.inl:148:165: note: #pragma message: GLM: rotateX function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: rotateX function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                     ^
/usr/include/glm/gtx/rotate_vector.inl: In function 'glm::detail::tvec4<T, P> glm::rotateY(const glm::detail::tvec4<T, P>&, const T&)':
/usr/include/glm/gtx/rotate_vector.inl:171:165: note: #pragma message: GLM: rotateX function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: rotateX function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                     ^
/usr/include/glm/gtx/rotate_vector.inl: In function 'glm::detail::tvec4<T, P> glm::rotateZ(const glm::detail::tvec4<T, P>&, const T&)':
/usr/include/glm/gtx/rotate_vector.inl:194:165: note: #pragma message: GLM: rotateZ function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: rotateZ function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                     ^
/usr/include/glm/gtx/rotate_vector.inl: In function 'glm::detail::tmat4x4<T, P> glm::orientation(const glm::detail::tvec3<T, P>&, const glm::detail::tvec3<T, P>&)':
/usr/include/glm/gtx/rotate_vector.inl:218:166: note: #pragma message: GLM: rotateZ function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #   pragma message("GLM: rotateZ function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                      ^
In file included from /usr/include/glm/gtx/vector_angle.hpp:86:0,
                 from /usr/include/glm/ext.hpp:129,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtx/vector_angle.inl: In function 'genType glm::angle(const genType&, const genType&)':
/usr/include/glm/gtx/vector_angle.inl:26:152: note: #pragma message: GLM: angle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: angle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                        ^
/usr/include/glm/gtx/vector_angle.inl: In function 'T glm::angle(const vecType<T, P>&, const vecType<T, P>&)':
/usr/include/glm/gtx/vector_angle.inl:45:152: note: #pragma message: GLM: angle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: angle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                        ^
/usr/include/glm/gtx/vector_angle.inl: In function 'T glm::orientedAngle(const glm::detail::tvec2<T, P>&, const glm::detail::tvec2<T, P>&)':
/usr/include/glm/gtx/vector_angle.inl:65:160: note: #pragma message: GLM: orientedAngle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: orientedAngle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                ^
/usr/include/glm/gtx/vector_angle.inl: In function 'T glm::orientedAngle(const glm::detail::tvec3<T, P>&, const glm::detail::tvec3<T, P>&, const glm::detail::tvec3<T, P>&)':
/usr/include/glm/gtx/vector_angle.inl:90:160: note: #pragma message: GLM: orientedAngle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.
 #  pragma message("GLM: orientedAngle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
                                                                                                                                                                ^
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp: In member function 'virtual void VSPGraphic::ArcballCam::load(int)':
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:83:50: error: no matching function for call to 'translate(float&, float&, float)'
     _tMat = glm::translate( _pan.x, _pan.y, 0.0f );
                                                  ^
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:83:50: note: candidates are:
In file included from /usr/include/glm/gtc/matrix_transform.hpp:292:0,
                 from /usr/include/glm/ext.hpp:71,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtc/matrix_transform.inl:36:43: note: template<class T, glm::precision P> glm::detail::tmat4x4<T, P> glm::translate(const glm::detail::tmat4x4<T, P>&, const glm::detail::tvec3<T, P>&)
  GLM_FUNC_QUALIFIER detail::tmat4x4<T, P> translate
                                           ^
/usr/include/glm/gtc/matrix_transform.inl:36:43: note:   template argument deduction/substitution failed:
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:83:50: note:   mismatched types 'const glm::detail::tmat4x4<T, P>' and 'float'
     _tMat = glm::translate( _pan.x, _pan.y, 0.0f );
                                                  ^
In file included from /usr/include/glm/gtx/transform.hpp:82:0,
                 from /usr/include/glm/gtx/rotate_vector.hpp:44,
                 from /usr/include/glm/ext.hpp:120,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtx/transform.inl:13:43: note: template<class T, glm::precision P> glm::detail::tmat4x4<T, P> glm::translate(const glm::detail::tvec3<T, P>&)
  GLM_FUNC_QUALIFIER detail::tmat4x4<T, P> translate(
                                           ^
/usr/include/glm/gtx/transform.inl:13:43: note:   template argument deduction/substitution failed:
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:83:50: note:   mismatched types 'const glm::detail::tvec3<T, P>' and 'float'
     _tMat = glm::translate( _pan.x, _pan.y, 0.0f );
                                                  ^
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp: In member function 'virtual void VSPGraphic::ArcballCam::pan(int, int, int, int)':
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:165:50: error: no matching function for call to 'translate(float&, float&, float)'
     _tMat = glm::translate( _pan.x, _pan.y, 0.0f );
                                                  ^
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:165:50: note: candidates are:
In file included from /usr/include/glm/gtc/matrix_transform.hpp:292:0,
                 from /usr/include/glm/ext.hpp:71,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtc/matrix_transform.inl:36:43: note: template<class T, glm::precision P> glm::detail::tmat4x4<T, P> glm::translate(const glm::detail::tmat4x4<T, P>&, const glm::detail::tvec3<T, P>&)
  GLM_FUNC_QUALIFIER detail::tmat4x4<T, P> translate
                                           ^
/usr/include/glm/gtc/matrix_transform.inl:36:43: note:   template argument deduction/substitution failed:
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:165:50: note:   mismatched types 'const glm::detail::tmat4x4<T, P>' and 'float'
     _tMat = glm::translate( _pan.x, _pan.y, 0.0f );
                                                  ^
In file included from /usr/include/glm/gtx/transform.hpp:82:0,
                 from /usr/include/glm/gtx/rotate_vector.hpp:44,
                 from /usr/include/glm/ext.hpp:120,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtx/transform.inl:13:43: note: template<class T, glm::precision P> glm::detail::tmat4x4<T, P> glm::translate(const glm::detail::tvec3<T, P>&)
  GLM_FUNC_QUALIFIER detail::tmat4x4<T, P> translate(
                                           ^
/usr/include/glm/gtx/transform.inl:13:43: note:   template argument deduction/substitution failed:
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:165:50: note:   mismatched types 'const glm::detail::tvec3<T, P>' and 'float'
     _tMat = glm::translate( _pan.x, _pan.y, 0.0f );
                                                  ^
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp: In member function 'virtual void VSPGraphic::ArcballCam::pan(float, float)':
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:175:50: error: no matching function for call to 'translate(float&, float&, float)'
     _tMat = glm::translate( _pan.x, _pan.y, 0.0f );
                                                  ^
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:175:50: note: candidates are:
In file included from /usr/include/glm/gtc/matrix_transform.hpp:292:0,
                 from /usr/include/glm/ext.hpp:71,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtc/matrix_transform.inl:36:43: note: template<class T, glm::precision P> glm::detail::tmat4x4<T, P> glm::translate(const glm::detail::tmat4x4<T, P>&, const glm::detail::tvec3<T, P>&)
  GLM_FUNC_QUALIFIER detail::tmat4x4<T, P> translate
                                           ^
/usr/include/glm/gtc/matrix_transform.inl:36:43: note:   template argument deduction/substitution failed:
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:175:50: note:   mismatched types 'const glm::detail::tmat4x4<T, P>' and 'float'
     _tMat = glm::translate( _pan.x, _pan.y, 0.0f );
                                                  ^
In file included from /usr/include/glm/gtx/transform.hpp:82:0,
                 from /usr/include/glm/gtx/rotate_vector.hpp:44,
                 from /usr/include/glm/ext.hpp:120,
                 from /home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:2:
/usr/include/glm/gtx/transform.inl:13:43: note: template<class T, glm::precision P> glm::detail::tmat4x4<T, P> glm::translate(const glm::detail::tvec3<T, P>&)
  GLM_FUNC_QUALIFIER detail::tmat4x4<T, P> translate(
                                           ^
/usr/include/glm/gtx/transform.inl:13:43: note:   template argument deduction/substitution failed:
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.1/src/vsp_graphic/src/ArcballCam.cpp:175:50: note:   mismatched types 'const glm::detail::tvec3<T, P>' and 'float'
     _tMat = glm::translate( _pan.x, _pan.y, 0.0f );
                                                  ^
make[2]: **\* [src/vsp_graphic/CMakeFiles/vsp_graphic.dir/src/ArcballCam.cpp.o] Error 1
make[1]: **\* [src/vsp_graphic/CMakeFiles/vsp_graphic.dir/all] Error 2
make: **\* [all] Error 2

---

I tried 3-Alpha and received the same results.  I am using glm version 0.9.5.3  I added -fpermissive to the CXXFLAGS through cmake and the same error showed up.

Cheers,

Fred

**Comment by ramcdona** [comment]
This was most likely resolved long ago.  Please try 3.10.0 and let us know if you still have problems.
