### ISSUE TITLE
VSPAERO Results Manager GUI Legend Entry Labels Incorrect (3.32.2)

### ISSUE THREAD

**Issue by brandon-litherland** [OpenVSP/OpenVSP#259]
The Legend GUI in the VSPAERO Results Manager is incorrectly showing other characters in lieu of the usual condition description for both the Convergence and Load Dist. tabs.  The Sweep, Cp Slice, and Unsteady legend entries seem to be unaffected.

![image](https://user-images.githubusercontent.com/83711375/231242780-4edd9c19-45e2-4d33-ad5a-6195146b8868.png)

![image](https://user-images.githubusercontent.com/83711375/231242875-17766aaf-8b90-4d5e-b474-ea5c615af2c0.png)

**Comment by ramcdona** [comment]
I've already got this one fixed for the next version.  Thanks for reporting it.

**Comment by ramcdona** [comment]
3.33.0 Should have a fix for this
