### ISSUE TITLE
MaterialMgr.cpp

### ISSUE THREAD

**Issue by fishforbreakfast** [OpenVSP/OpenVSP#26]
Hi,

Just building 2.9.3 and ran into this with MaterialMgr.cpp

[ 70%] Building CXX object src/geom_core/CMakeFiles/geom_core.dir/MaterialMgr.cpp.o
/home/fred/src/OpenVSP/OpenVSP-OpenVSP_2.9.3/src/geom_core/MaterialMgr.cpp:4:21: fatal error: ParmMGr.h: No such file or directory
 #include "ParmMGr.h"
                     ^
compilation terminated.

I took a look at the includes and noticed that ParmMGr.h was actually ParmMgr.h so I changed the statement in MaterialMgr.cpp to match:

#include "ParmMgr.h"

instead of the original which caused the error.

Cheers,

Fred

**Comment by ramcdona** [comment]
Fixed in 10c03d8e36379e935c06b41d7ec78c6e5904a5d6
