### ISSUE TITLE
compile openvsp on HPC with “-DVSP_NO_GRAPHICS=true”

### ISSUE THREAD

**Issue by Zcaic** [OpenVSP/OpenVSP#260]
when I compile openvsp on HPC with “-DVSP_NO_GRAPHICS=true”， it works well.
But after I install OpenVSP python package, I use "import openvsp", it raises 
"ERROR 7: VSPAERO Viewer Not Found.
        Expected here: /opt/mambaforge/envs/vsp/lib/python3.9/site-packages/openvsp/vspviewer ".

how I solve it when I compile OpenVSP without gui, it seems "python openvsp package" needs vspviewer still.

**Comment by ramcdona** [comment]
3.33.0 Should silence this warning in this situation.
