### ISSUE TITLE
Memory leaks when using with Python API

### ISSUE THREAD

**Issue by trilbytim** [OpenVSP/OpenVSP#261]
Using the Python API with OpenVSP 3.32.2 on Ubuntu 22.04 when running many hundreds of iterations of a design (with intent to automatically optimise) it eventually fills up all available memory and crashes.

Example cases are uploaded (.txt extensions added to allow uploading to github). Repeatedly running a VLM analysis on the same model causes this behaviour (as seen in memtest-VLM.py). Closing and reopening the file does not solve this, in fact simply repeatedly opening a file causes the memory to fill up (albeit at a slower rate)- see very simple file memtest.py

[memtest.py.txt](https://github.com/OpenVSP/OpenVSP/files/11254902/memtest.py.txt)
[memtest-VLM.py.txt](https://github.com/OpenVSP/OpenVSP/files/11254903/memtest-VLM.py.txt)
[apitest.vsp3.txt](https://github.com/OpenVSP/OpenVSP/files/11254906/apitest.vsp3.txt)

**Comment by ramcdona** [comment]
I believe this is fixed in 3.33.0.  Please try it out and let me know.
