### ISSUE TITLE
AVL integration (feature request)

### ISSUE THREAD

**Issue by monkeypants** [OpenVSP/OpenVSP#27]
As per this discussion about vorlax availability:

https://groups.google.com/forum/m/#!topic/openvsp/DbtpXYQ_ogU

AVL integration would be a really great new feature. Please :)

**Comment by ramcdona** [comment]
We've created and integrated VSPAERO to address this need.  It is included in any release after 3.1.0 e76b1b23cf5f1ca7e38b7f2f03c9bcacf01383f1 .

**Comment by monkeypants** [comment]
Thanks! that's great news.

Is there any documentation or examples that I could follow up?
