### ISSUE TITLE
Bug: Background JPEG problem in v3.0.2

### ISSUE THREAD

**Issue by newtype0123** [OpenVSP/OpenVSP#28]
So I was trying out the latest v3. I tried importing a JPEG image in the background but it shows up "very wrong". I tried the same image in v2.3.0 and it was imported correctly. 

I tried saving the JPEG in different programs (including Photoshop with various options) and the image will still not show up properly in v3. For a good 20 minutes, I can't figure why some JPEG would work and some won't work in v3.

I uploaded the actual file here. 
![yf19 top](https://cloud.githubusercontent.com/assets/10675004/5881005/fbca3782-a2f1-11e4-8aa6-c5b76c0a1f5e.jpg)
Anyway, please look into it.

By the way, all the old models (and the ones available at the VSP Hangar) generated in v2 can't open in v3. Is that intended?

**Comment by ramcdona** [comment]
The background reading code has been substantially updated since 3.0.2.  Please try a recent version (3.10.0 or newer) and let us know if you still have trouble.

Some time ago, a v2 import feature was added.  It isn't perfect, but it should do a decent job of opening your v2 models.
