### ISSUE TITLE
Help menu item do not do anything

### ISSUE THREAD

**Issue by pmsagdeo** [OpenVSP/OpenVSP#29]
In the latest version, the help menu items do not do anything, No information is displayed and no online help opens in the browser.  Is anyone else experiencing this?  Thanks.

**Comment by ramcdona** [comment]
For better or worse, there was no online help -- what you were experiencing was expected.

The menu item for online help was removed to eliminate user confusion.

If you have general questions about OpenVSP, the best place to ask them is the Google Group.
