### ISSUE TITLE
CFDmesh creates uneasonable shaped elements

### ISSUE THREAD

**Issue by mike15083** [OpenVSP/OpenVSP#294]
CFDmesh created a bad mesh. I have been able to reduce the problem to this size:

![Screenshot 2024-04-30 111141](https://github.com/OpenVSP/OpenVSP/assets/67758094/f278b54c-a3f9-4bd1-95e1-bbb92174454e)

A closer look at the poor mesh shows:
![Screenshot 2024-04-30 111150](https://github.com/OpenVSP/OpenVSP/assets/67758094/3cad0371-50d1-4400-8f1f-13d186e880c4)

and if I zoom in finer and use color to show shapes better:
![Screenshot 2024-04-30 111211](https://github.com/OpenVSP/OpenVSP/assets/67758094/49f4a304-fae2-46ec-80cd-cbba08fdfcf5)

It is easy to get around the issue, but it appears in other models and occurs without any warning issued. I would like to use OpenVSP in an optimization process and will not have the ability to review a mesh before using it.
[wingmesh bug 1.zip](https://github.com/OpenVSP/OpenVSP/files/15169551/wingmesh.bug.1.zip)

**Comment by ramcdona** [comment]
I can not duplicate this case on my machine with the file supplied.

I know that this sort of thing can happen -- but as you say, it is relatively fragile to other settings.

I will keep an eye open for cases like this that I can debug, but I'm going to close this issue as it does not provide a test case I can use.
