### ISSUE TITLE
Problem about AngelScript InitGUI();

### ISSUE THREAD

**Issue by Anastasia-CS** [OpenVSP/OpenVSP#295]
I used InitGUI() API in a .vspscipt file. There was only " InitGUI()" in main function. However, when I run it with cmd, "ERR  : No matching symbol 'InitGUI'" is shown.
How can I use InitGUI() correctly.

The content of my AngelScript:
void main()
{
	InitGUI();
	StartGUI();
}

**Comment by ramcdona** [comment]
Please don't post to the Google Group and file an Issue here at the same time.  Closing here to discuss on the Group.
