### ISSUE TITLE
OpenVSP installation process should be revisted (very hard for downstream packaers to package

### ISSUE THREAD

**Issue by luzpaz** [OpenVSP/OpenVSP#310]
Some feedback from downstream nixOS package repo:
> It just deviates from the standard way by a far margin, thus building it is really not as straightforward as just using automake to derive which build type it is. Just knowing it's cmake and providing flags will fail as it doesn't know that it has to build the libraries first or the openvsp build will fail. All I can say right now is that I've never seen a software ship its dependencies as zip files and then require the user to build them. 

Source: https://github.com/NixOS/nixpkgs/pull/353536#issuecomment-2468603992

**Comment by ramcdona** [comment]
Closing per commentary in linked thread.
