### ISSUE TITLE
'vsp.SetParmVal(wid, "Sym_Rot_N", "XForm", int(3) )' doesn't work on the model

### ISSUE THREAD

**Issue by RebelYoung** [OpenVSP/OpenVSP#311]
I use the python api for automated generate models.
However, it doesn't work for the model by `'vsp.SetParmVal(wid, "Sym_Rot_N", "XForm", int(3) )'`

I have tried other variable on `'XForm'` like `'Z_Rel_Location'`, `'X_Rel_Rotation'`,etc.
All of them work efficiently.

There is no error when execute 'vsp.SetParmVal(wid, "Sym_Rot_N", "XForm", int(3) )', but `vsp.GetParmVal(wid, "Sym_Rot_N", "XForm")` return `0.0` not `3`, which original value is `11` in the based `.vsp` file.

![图片](https://github.com/user-attachments/assets/f4fb7c4c-2ffc-4b69-85a3-d0076fbc5a18)

![图片](https://github.com/user-attachments/assets/c2e31f1f-f749-4a7d-b67e-70c67a4f0d77)

**Comment by RebelYoung** [comment]
I tried `vsp.SetParmVal(vsp.FindParm(wid,'Sym_Rot_N','XForm'),int(3))` , but it also didn't work.
`vsp.GetParmVal(wid,'Sym_Rot_N','XForm')` returned `0.0` not `3`.
![图片](https://github.com/user-attachments/assets/144dd69f-9f8d-4d6b-9d3c-d10ae415b37c)

**Comment by RebelYoung** [comment]
I found `vsp.FindParm(wid,'Sym_Rot_N','XForm')` return `''`, not Parm ID.
So is there no `'Sym_Rot_N'` value in openvsp python script ?
![图片](https://github.com/user-attachments/assets/0e19b722-f4a0-458a-8c9e-4c0ab4e2c733)

**Comment by ramcdona** [comment]
Questions like this are generally best asked in the OpenVSP Google Group.

Try:

`vsp.SetParmVal(wid, "Sym_Rot_N", "XForm", int(3) )
`

Note that the parameter group is `Sym` not `XForm`.  You can see this in the second image where you pulled up the information about the `Sym_Rot_N` parm.
