### ISSUE TITLE
SVG version of the logo

### ISSUE THREAD

**Issue by SylvainCorlay** [OpenVSP/OpenVSP#313]
Hello! Is there an SVG version of the OpenVSP logo?

We would like to use it as a file icon for the vsp3 file format in JupyterLab.

**Comment by ramcdona** [comment]
Here ya go.
![OpenVSP Logo](https://github.com/user-attachments/assets/02601134-87a7-4e80-8d54-cc2634e505d4)
![OpenVSP Logo Twitter ai](https://github.com/user-attachments/assets/bfe35395-359d-4fa3-918d-2711582ac9dc)

**Comment by SylvainCorlay** [comment]
Thanks! 🙏

**Comment by ramcdona** [comment]
The originals of these were actually created in Adobe Illustrator, so the files are *.ai.  I had an SVG of the OpenVSP (line version) one, but I used Inkscape to open the *.ai and write out the SVG of the

Open
VSP

one (box version).  I no longer have access to Illustrator and GitHub won't let me upload that format.

If you would prefer the *.ai file, send me an email.  You might also try re-creating it from the line version.

I can't tell for sure, but there seemed to be some clipping at the left hand side of the O in the box version.
