### ISSUE TITLE
Awave slicing crashes while slicing touching wings

### ISSUE THREAD

**Issue by Lemon-L-Lime** [OpenVSP/OpenVSP#34]
1. Create a wing.
2. Create another wing and make it looking like a second section of a single wing:
   - root of 2nd wing and tip of 1st one have to be approximately equal and placed at close coordinates,
   - strong condition: Yloc of 2nd root must be exactly equal to 1st wing span. E.g., if the span of the 1st wing is 3.0 units, Yloc the 2nd one must be 3.0 too. Neither intersection (2.99) nor gap (3.01) cause crash.
3. Open awave slice dialog, set Num Slices = 100, Mach Angle = 90, all other default, and try to start slicing.

v. 3.04 - 3.1.1

**Comment by ramcdona** [comment]
The AWave Slicing has been deprecated and removed as of version 3.7.0.  It was replaced with a comprehensive new wave drag tool.

Please report if your problem still persists.
