### ISSUE TITLE
VSPAero Viewer will not open - "cannot find Font"

### ISSUE THREAD

**Issue by BrassAPE** [OpenVSP/OpenVSP#36]
OpenVSP 3.1.2 running on Windows 8.1 

I have run a VSPAero analysis for the 1st time. 

When I launch the VSPAero Viewer I get an error message "Could not open the font file for writing! "

Any suggestions?

**Comment by ramcdona** [comment]
Please test with a recent version (say 3.19.0) and re-open if the problem persists.
