### ISSUE TITLE
#include "backgroundScreen.h" still present in ManageBackgroundScreen.h for 3.2.1

### ISSUE THREAD

**Issue by fishforbreakfast** [OpenVSP/OpenVSP#38]
Hi,

Just building 3.2.1  Thank you for all of your hard work and for OpenVSP!

I checked with the master branch and the reference to backgroundScreen.h has been removed but in ManageBackgroundScreen.h in the tar archive for 3.2.1, it is still there.  Here is a "snip" of the file:

//
// This file is released under the terms of the NASA Open Source Agreement (NOSA)
// version 1.3 as detailed in the LICENSE file which accompanies this software.
//
//
//////////////////////////////////////////////////////////////////////

#ifndef MANAGE_BACKGROUND_SCREEN_H
#define MANAGE_BACKGROUND_SCREEN_H

#include "backgroundScreen.h"
#include "ScreenBase.h"
#include "Parm.h"

using namespace std;

//class ScreenMgr;
class ManageBackgroundScreen : public BasicScreen

I just removed the #include "backgroundScreen.h" and continued building OpenVSP without issues.

Hope this helps.

Cheers,

Fred

**Comment by ramcdona** [comment]
Fixed by b1c6cdb148a27e2f68c3c23a98e61a4249fad381
