### ISSUE TITLE
VSP crashes when loading airfoil file

### ISSUE THREAD

**Issue by kmisegades** [OpenVSP/OpenVSP#41]
I defined a simple wing (approx. Klemm KL 107) with two sections, three airfoils.  The #1 (wing root) and #2 airfoils are both NACA 23018, the wing tip is NACA 23012. All airfoil files obtained from the UIUC database. The two NACA 23018 airfoils worked fine.  When I loaded the 23012 file though the tip remained a circle with the desired chord.  I eventually gave up with this file and set a NACA 2212 airfoil instead.  I just now tried the latest release 3.2.3. When I attempt to switch the tip airfoil from NACA 2212 to reading the 23012, VSP crashes.  It also crashes in version 3.2.2      I am happy to send someone the VSP file.

Is there a means to generate rounded wing tips?

Any chance you can one day offer NACA 5-series airfoils in addition to 4- and 6-series ?    

Many thanks, so far it looks like a powerful tool.   Kent Misegades, Cary, NC

**Comment by ramcdona** [comment]
The new foil types you're asking about were added a few versions ago.  Rounded tips were added a long time ago.  I also think some bugs with reading file airfoils have been fixed.  Please test with a recent version (say 3.19.0) and re-open if the problem persists.
