### ISSUE TITLE
Build fails on Linux, FLTK headers not found.

### ISSUE THREAD

**Issue by fishforbreakfast** [OpenVSP/OpenVSP#44]
Hi,

Thanks for this new release!  I built 3.5.2 successfully but had to correct some of the header files in src/gui_and_draw/  I have included a patch of what I modified.  Specifically, some of the #includes had a small .h whereas the includes in /usr/include/FLTK/FL have *.H.  Maybe this doesn't affect anyone else.  If not then I can make due.

Cheers,

Fred

[gui_and_draw-3.5.2.diff.patch.txt](https://github.com/OpenVSP/OpenVSP/files/148496/gui_and_draw-3.5.2.diff.patch.txt)

**Comment by ramcdona** [comment]
Fixed by 0d40cd8a876ca858afa6ad656e5e14c728eaa695
