### ISSUE TITLE
Please add a running an example with the api first time tutorial

### ISSUE THREAD

**Issue by Codeguyross** [OpenVSP/OpenVSP#45]
I would like to run the software at least once but cannot get even the basic example to work. What steps do I need to do to use the api to run an example?

Any help would be appreciated!

**Comment by cibinjoseph** [comment]
This issue may be closed if the merged API example is found adequate. If not, drop a comment and _someone_ could build a tutorial on that.

**Comment by ramcdona** [comment]
Please ask general questions in the OpenVSP Google Group.

If you have specific bug reports with reproducible steps and conditions, please open a new issue for those here.
