### ISSUE TITLE
Anglescript x**y does not work, must use pow(x,y)

### ISSUE THREAD

**Issue by nbrakeES** [OpenVSP/OpenVSP#53]
(This may be an issue in Anglescript and not directly in VSP)

When using the scripting interface a *\* operation generates an error although this is the base math operator for calculating an exponent in Anglescript.
![image](https://cloud.githubusercontent.com/assets/16159836/17525973/07c28500-5e1a-11e6-8046-3c3732e4a125.png)

The *\*  expression in the script must be replaced with a call to pow()
![image](https://cloud.githubusercontent.com/assets/16159836/17526002/31d74484-5e1a-11e6-8ea6-491eb5306d3c.png)

AngleScript *\* documentation: (ref: http://www.angelcode.com/angelscript/sdk/docs/manual/doc_expressions.html#math)
![image](https://cloud.githubusercontent.com/assets/16159836/17525865/88ae5f1e-5e19-11e6-9c59-a1a64d14c2e0.png)

AngleScript pow() documentation: (ref: http://www.angelcode.com/angelscript/sdk/docs/manual/doc_addon_math.html#doc_addon_math_1)
![image](https://cloud.githubusercontent.com/assets/16159836/17526081/90ef5e2a-5e1a-11e6-8bcc-7c2b392d5c22.png)

**Comment by ramcdona** [comment]
Fixed by updating AngelScript to 2.31.2 in d39494378df8.
