### ISSUE TITLE
OpenVSP Workshop 2016 - videos

### ISSUE THREAD

**Issue by Symbian9** [OpenVSP/OpenVSP#55]
Please, duplicate videos from NASA site...
- http://nari.arc.nasa.gov/vsp

... to OpenVSP channel on Youtube
- https://m.youtube.com/channel/UCgkncj4tKePKtX6mTcDHTDw

On NASA site to play them need Flash, but in most cases Flash technology and its addons in actual webbrowsers now are discountinied!

**Comment by chrissilva** [comment]
Also, it looks like J.R.'s presentation video from the first day on conformal components got lost. Both links point to the demo instead.

**Comment by ramcdona** [comment]
Unfortunately, we were never able to get the videos out of the NARI system and they appear to be dead now.
