### ISSUE TITLE
Download page give error 404

### ISSUE THREAD

**Issue by Symbian9** [OpenVSP/OpenVSP#56]
"Download" page on official site give error 404
* http://openvsp.org/download.php

So, what problem here?
Can you give direct links to binary builds?

**Comment by ramcdona** [comment]
Seems to be working again now.

Files are located in a static location -- the PHP creates a nice page that indicates the version number.

Start here:
http://openvsp.org/zips/current/

Then pick your mac/windows preference.  The latest version is always in that directory.
