### ISSUE TITLE
Incorrect detection of control surfaces on multiple wings with OpenVSP/VSPAERO

### ISSUE THREAD

**Issue by nbrakeES** [OpenVSP/OpenVSP#58]
Multiple surfaces on multiple wing geometries are not communicated from OpenVSP to VSPAERO properly.  This bug was noticed with the following procedure
1. add wing
2. add control surface as subsurface with default options
3. set subsurface name to fwd_elevons
4. add 2nd wing and translate aft
5. add control surface as ubsurface with default options
6. set subsurface name to aft_elevons
7. open VSPAERO GUI from menu: Analysis-->VSPAERO
8. generate geometry
9. create new setup

Detected in OpenVSP v3.9.0
[test_multisurface_control.zip](https://github.com/OpenVSP/OpenVSP/files/443630/test_multisurface_control.zip)

**Comment by ramcdona** [comment]
Please test with 3.19.0 and re-open if the problem persists.
