### ISSUE TITLE
VSP hang during update of Solver console FL_Text_Display

### ISSUE THREAD

**Issue by nbrakeES** [OpenVSP/OpenVSP#61]
The FL_Text_Display update enters a loop with a corrupt loop end condition of INT_MAX number of characters.  This causes VSP to hang until the loop terminates.  This was observed in OpenVSP v3.9.0 and can be replicated most easily by running a vspaero batch mode calculation and rapidly scrolling the mouse wheel up and down within the Solver Console text display.

**Comment by ramcdona** [comment]
@justingravett, please look into this and fix or close.

**Comment by ramcdona** [comment]
I believe this is fixed.  If not, please let me know how to reproduce.
