### ISSUE TITLE
3D XSec

### ISSUE THREAD

**Issue by Damov** [OpenVSP/OpenVSP#70]
Hello everyone,

I wanted to ask if it will be possible in later versions to model sections of the fuselage, where some points of the sections you can move along the x-axis. I would like to model sharp front windows of an airliner fuselage by defining an XSec and move some points normal to the YZ-layer.

Btw, is the B-Spline modelling of XSecs already available?

Kind regards,
Daniel

**Comment by ramcdona** [comment]
3D XSec was added in 3.27.0.  You can probably use that to capture more details of the windscreen of an airliner.

Bezier edit XSecs was added in 3.19.0.

Generally speaking, it is better to ask questions on the Google Group.
