### ISSUE TITLE
Build fails first time, works in second run

### ISSUE THREAD

**Issue by fernape** [OpenVSP/OpenVSP#74]
Tested on FreeBSD. OpenVSP 3.10 works fine. With 3.11, the first time make is run, the compilation fails with this message:
`[ 54%] Building CXX object src/util/CMakeFiles/util.dir/SuperEllipse.cpp.o
<built-in>: In function 'float abs(float)':
<built-in>: warning: conflicts with previous declaration here [-Wattributes]
<built-in>: In function 'float abs(float)':
<built-in>: warning: conflicts with previous declaration here [-Wattributes]
[ 55%] Building CXX object src/util/CMakeFiles/util.dir/SVGUtil.cpp.o
In file included from /usr/home/fernape/redports.org/fernape/cad/openvsp/work/OpenVSP-OpenVSP_3.11.0/src/util/SVGUtil.cpp:11:0:
/usr/home/fernape/redports.org/fernape/cad/openvsp/work/OpenVSP-OpenVSP_3.11.0/src/util/SVGUtil.h:17:21: fatal error: XmlUtil.h: No such file or directory
 #include "XmlUtil.h"
                     ^
compilation terminated.
--- src/util/CMakeFiles/util.dir/SVGUtil.cpp.o ---
*** [src/util/CMakeFiles/util.dir/SVGUtil.cpp.o] Error code 1
`
Running make again without any modifications makes OpenVSP build fine.

The dependency of XmlUtil.h was introduced in 3.11 and I can see the variable XMLVSP_INCLUDE_DIR is properly set and I can not spot the problem so I can not provide a patch.

Any ideas?

**Comment by ramcdona** [comment]
There was a circular dependency between src/util and src/xmlvsp.  I moved SVGUtil to geom_core in 697b3fa676bfb8.  Try the tip of master or https://github.com/OpenVSP/OpenVSP/tree/BuildFixes rather than the tagged 3.11.0.

**Comment by fernape** [comment]
On Sat, Mar 11, 2017 at 7:56 PM, Rob McDonald <notifications@github.com>
wrote:

> There was a circular dependency between src/util and src/xmlvsp. I moved
> SVGUtil to geom_core in 697b3fa
> <https://github.com/OpenVSP/OpenVSP/commit/697b3fa676bfb89ba929f8ab06f13b9d91ea9b31>.
> Try the tip of master or https://github.com/OpenVSP/
> OpenVSP/tree/BuildFixes rather than the tagged 3.11.0.
>

Got it.

Thanks!
