### ISSUE TITLE
Channel Wing

### ISSUE THREAD

**Issue by Symbian9** [OpenVSP/OpenVSP#75]
How create "channel wing"? Is it supported by OpenVSP?

For example, An-181
![Antonov An-181 aka "Изделие 181"](http://military-informant.com/wp-content/uploads/2014/11/i181-3.jpg)

**Comment by ramcdona** [comment]
Try this...

http://hangar.openvsp.org/vspfiles/334

**Comment by Symbian9** [comment]
@ramcdona, THANK YOU! ;)
