### ISSUE TITLE
Aircraft Model Corrupted/File Cannot be Parsed After Saving Mac OpenVSP v3.12.1

### ISSUE THREAD

**Issue by RigelFive** [OpenVSP/OpenVSP#77]
I experienced a crash after attempting to group the control surfaces in OpenVSP.  After completing the grouping, I experienced a crash immediately after attempting to run the parasitic drag feature in the analysis menu.

My OpenVSP aircraft model (which worked pretty well in OpenVSP 3.11) is not able to be opened and is considered 100% corrupted (I do have a backup).  My best memory of what I did was 'save the model' right after performing the control surface grouping.

First inclination is to rebuild the model in OpenVSP 3.12.1 in order to flush out any incompatibilities between file versions.  Really looking forward to future capabilities!

**Comment by ramcdona** [comment]
We may have fixed this for the next version -- but I'm not sure.  Can you send a file and exact steps to recreate the problem to my email?

**Comment by ramcdona** [comment]
Please try with 3.13.0 and update us here.
