### ISSUE TITLE
Errors in Rotor-Induced Velocities

### ISSUE THREAD

**Issue by smaero** [OpenVSP/OpenVSP#78]
It seems that there are some errors in the rotor-induced velocity calcs in RotorDisk.C (the function ROTOR_DISK::Velocity).

A couple of the errors are with the radial velocity (Velocity_R) calculations.  From Conway, "Analytical solutions for the actuator disk with variable radial distribution of load", the equation on line 297 should be:

if ( r > 0. && alpha > 0. ) Term1 = ABS(z)*(1./alpha - alpha)/(2.*r);

Also, the radial velocity is not being computed correctly when the axial distance, z, is zero and the radial distance is greater than the rotor radius.  There should be an additional line:

if ( r > RotorRadius && z==0. ) Term1 = 0.5 * sqrt(1.0 - RotorRadius*RotorRadius/r/r);

There might be a problem with the calculation for tangential velocity, Velocity_T.  The equations on lines 339 to 343 are a mixture of hover and non-hover solutions (from Wayne Johnson's "Helicopter Theory").  When I work through the non-hover solution on pg 45, I get a much more convoluted Cd/Cl term than what Johnson provides for hover (which is the term used in the code).  Maybe for typical values of freestream velocity and prop loading, it reduces to the hover solution that's used in the code.

It seems like the tangential velocity from Johnson is based on different assumptions than the elliptically-loaded prop for which the Conway solutions hold.  For example, if one compares Conway's distribution of axial velocity (pg 351) with Johnson's (pg 44), they are considerably different.  Johnson's equation for tangential velocity is based on having f(V_axial,V_tangential)=constant.  So, maybe mixing Conway's V_axial with Johnson's V_tangential is not appropriate.  That said, Conway's velocity profiles don't seem to match any I've found in any other source.  **(I'm new to propeller analysis, so it's possible that I'm completely misunderstanding things.)**

**Comment by arocketguy** [comment]
Yup, the first line was a bug... it's correct in another version I had, so I obviously 'cleaned it up' at some point and made the mistake. The 2nd Term1 case was a good catch, I thought I had worked out the the full forms drop to the limiting cases, but in fact for that situation it does not... It likely did not affect many people as odds are you are not often evaluating it right at z=0 for any one panel. I've made fixes for these and the should get rolled in by Rob at some point.

As to Johnson's tangential - yes, I'm mixing stuff up there. Conway's tangential model is completely missing the viscous portion and what I did was an attempt at a very simple fix that required no extra inputs from the user. 

-Dave
