### ISSUE TITLE
[Whishlist] Export custom script from geometry

### ISSUE THREAD

**Issue by Damov** [OpenVSP/OpenVSP#79]
Hello everyone,

I know OpenVSP for a long time. However, last versions of OpenVSP made this software a quite a nice tool box. I start to use custom scripts to define my components. Unfortunately, I am missing a kind of "Macro recording" function, which generates and exports a custom script to a file. For example, if I want to do a parameterized custom script of an aero fan engine, I would like to model it including blades, etc... with VSP and then export to file, edit this file and define based on that file a custom component. Is it possible to include this function in the next upgrade?

Kind regards,
Daniel

**Comment by ramcdona** [comment]
Adding a macro recording capability is a major endeavor -- and also a long-term maintenance burden.  We had that in v2 and will not take it on again in v3.

I could imagine someone could write a program that would take a *.vsp3 file as input and would generate another Python program to generate the same model using the API.  You could then modify that program to have your parameterized geometry.

However, why not just use the *.vsp3 file as a baseline and use the API to make the changes you need made?  Why re-create the geometry every time?
