### ISSUE TITLE
Issues build under Ubuntu 16.04 

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [OpenVSP/OpenVSP#87]
I've followed the instruction found at http://www.openvsp.org/wiki/doku.php?id=ubuntu_instructions#instructions_for_ubuntu_1604. I ran into the python version issue and fixed it by changing the find_package of the CMakelists.tx under in the python_api to 
`FIND_PACKAGE(PythonLibs 2.7 REQUIRED)`
Now I believe I'm running into the fluid issue. However I'm not sure how to proceed. I'm getting the following error:
`Built target vsp_graphic
make[2]: *** No rule to make target '/home/alexandre/Documents/Programs/OpenVSP/repo/src/fltk_screens/fluid', needed by 'fltk_screens/typeEditorFlScreen.h'.  Stop.
CMakeFiles/Makefile2:767: recipe for target 'fltk_screens/CMakeFiles/screens.dir/all' failed
make[1]: *** [fltk_screens/CMakeFiles/screens.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
`
In the CMakeCache.txt under the build folder, I have:
`FIND_PACKAGE_MESSAGE_DETAILS_FLTK:INTERNAL=[fltk_images;fltk_forms;fltk_gl;/usr/lib/x86_64-linux-gnu/libGL.so;fltk][/usr/lib/fltk;/usr/include][fluid][v()]`
however I don't understand how to change the path, delete the files under build and make.
If I change the CMakeCache.txt, it gets overwritten when I make.

**Comment by marcovanderbijl** [comment]
Hi!

use the method that builds the libraries first.
copy the fluid executable from
'/buildlibs/FLTK-prefix/bin'  into
'/repo/src/vsp_aero/viewer' and '/repo/src/fltk_screens'
to get over the fluid problem

then build the openvspexe and end with a
$ make package
use the packaged build to run the program from.
using packagebuild makes openvsp find the scripts for podman etc.

in the hope it helps and with best regards,
M.

**Comment by AlexandreBorowczyk** [comment]
Awesome it work perfectly!
Thanks for the help!

**Comment by marcovanderbijl** [comment]
I still use this thread (and the OP link to Ubuntu 16.04 build instructions) as my own build instruction manual.
I Just switched from Ubuntu16.04 to Mint18Sylvia (based on Ubuntu 16.04) and am
just leaving a breadcrumb for myself for next time:

add
python-dev
to the required dependencies list.
and also
sudo copy fluid executable to /usr/bin/
