### ISSUE TITLE
RFE: Wing Geometry export of Rib/Spar mesh

### ISSUE THREAD

**Issue by cevich** [OpenVSP/OpenVSP#9]
It would be generically useful if the Rib/Spar mesh could be export along with the wing-skin mesh when Export button clicked.  STL export would be fine, but export into some 2d format would be ideal.  Perhaps the same simple format used by air foil files?

Background: http://groups.google.com/group/openvsp/browse_thread/thread/589c49e20194e52d#

**Comment by ramcdona** [comment]
While I agree there is a lot of potential to use OpenVSP as a platform to develop model airplanes, there isn't any funding to support these use cases.

If someone from the modeling community were to step in to take on these changes, they would be welcomed.  Unfortunately, I do not have time to add them to the development plan.
