### ISSUE TITLE
Unit Conversion Issue

### ISSUE THREAD

**Issue by mxfeinberg** [OpenVSP/OpenVSP#90]
When a model is created using English units and is then exported to a different format in metric units, the stored model's units are changed, but its scale is not maintained.  For example, I made a wing with a span of 4 inches and when it was converted to a metric .STEP file, the wing became 4 millimeters.

**Comment by ramcdona** [comment]
OpenVSP doesn't really have any concept of units.  So, your model that you thought was in English units is really dimensionless in OpenVSP's opinion.

STEP files have a concept of units.  So, when you export it to a STEP file, you are informing the STEP file of the units you intend the model to be interpreted in.  No conversion happens, just interpretation.

This approach really made sense at the start -- but has gotten a bit difficult.  As OpenVSP has evolved, more and more things have needed to have a concept of units.  A few analyses, some pre-processing steps, some export formats, etc.  Each of them is handled in a similar way -- you must declare what units you want the model to be interpreted in.  Each of these is separate.  No scaling or conversion happens for you.

Perhaps if we were doing it again, we would have a centralized concept of units that was applied across the model.  However, it would be difficult to make that transition seamless and compatible at this point.
