### ISSUE TITLE
VSPAERO Viewer will not open - Possible MS Windows Security Issue?

### ISSUE THREAD

**Issue by BBFlyer1** [OpenVSP/OpenVSP#97]
I have been running openVSP for some time.  I recently switched to openVSP 3.14.2 which I think is great.  Thanks for all your hard work on this tool.  

I am having an issue, however.   When I run VSPAERO on a generic 1 section wing, the Solver seems to work just fine and the Results Manager window comes up when I start the solver, before I can I press the Results Manager Button.  The Launch Viewer button does not work (no viewer window is displayed) and when I try to run vspviewer manually (I copied the vsp desktop icon and changed the properties to try to start vspviewer.exe instead of vsp.exe), I get the following error Dialog box.  

"Windows protected your PC
Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

App: vspviewer.exe 
Publisher:  Unknown publisher 

Run anyway 		Don’t run "

When I press the “run anyway” dialog button, I get a window flash then the viewer is gone.  (When I try to run it from inside VSP, I don't get the flash)

I am running Windows 10 Home 64 bit OS Version 1709 Build 16299.192
on an Intel Core I5 x64 CPU M430 @ 2.27 Ghx.  With 4.00 GB Ram.
I am running Norton Version 22.11.2.7 for my antivirus security.

**Comment by ramcdona** [comment]
Please test with version 3.19.0 and re-open if the problem persists.
